aws_region         = "ap-south-1"
upload_bucket_name = "jainilgupta-upload-accelerator-frontend-hosting-bucket"
frontend_bucket_name     = "jainilgupta-accelerator-hosting-bucket"
cloudfront_price_class   = "PriceClass_100"
notification_email = "jainilgupta93@outlook.com"